name: CI/CD Pipeline (Railway)

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 3: Install dependencies (in myapp folder)
      - name: Install dependencies
        run: npm install
        working-directory: ./myapp

      # Step 4: Run tests (optional)
      - name: Run tests
        run: npm test || echo "No tests"
        working-directory: ./myapp

      # Step 5: Install Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Step 6: Deploy to Railway
      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_NAME }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        working-directory: ./myapp
